name: 🐧 Godot 4 Vulkan normal Repeater
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
  GODOT_BASE_BRANCH: master
  SCONS_CACHE_LIMIT: 4096

jobs:
  linux-sanitizer:
    runs-on: "ubuntu-22.04"
    name: Editor and project

    steps:
      - uses: actions/checkout@v3

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      # Install all packages (except scons) - also installs updated mesa drivers
      - name: Configure dependencies
        run: |
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EB8B81E14DA65431D7504EA8F63F0F2B90935439
          sudo add-apt-repository "deb https://ppa.launchpadcontent.net/kisak/turtle/ubuntu focal main"
          sudo apt update
          sudo apt-get install -qq mesa-vulkan-drivers

          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm \
            xvfb wget2 unzip scons git

      - name: Configure Project Data
        run: |

          echo "[rendering]" >> project.godot
          echo "renderer/rendering_method=\"forward_plus\"" >> project.godot

      - name: Download reproducer
        run: |
          wget -nv https://github.com/qarmin/Qarminer/releases/download/reproducer/find_minimal_godot_crash_02 -O reproducer
          chmod +x ./reproducer

      - name: Download Godot(GIT)
        run: |
          git clone https://github.com/godotengine/godot.git
          cd godot
          git checkout master
          cd ../

      - name: Compile Godot
        run: |
          cd godot
          scons -j2 dev_build=yes target=editor use_asan=yes use_ubsan=yes linker=gold
          cp bin/godot.linuxbsd.editor.dev.x86_64.san ../
          cd ../
          rm -rf godot

      # Make backup of project.godot
      - name: Backup project.godot
        run: |
          cp project.godot project.godot.old

      - name: Open Godot Editor
        run: |
          UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san -e --quit --audio-driver Dummy --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
          tail -n 300 sanitizers_log.txt > editor_results.txt

      - name: Store editor results
        uses: actions/upload-artifact@v3
        with:
          name: editor-results
          path: editor_results.txt

      - name: Check Godot Editor Log
        run: |
          misc/check_ci_log.py editor_results.txt

      - name: Configure Project Data
        run: |
          rm timer.txt || true
          rm CRASH_INFO -rf || true
          rm memory_usage.txt || true
          rm results.txt || true
          rm crash_reproduce.gd || true
          echo "" > settings.txt
          cp project.godot.old project.godot

      - name: Run Project Multiple Times - One run ~120 seconds - 60 ~ 2 hours
        run: |
          for iteration in {1..60}; do
            for i in {0..50}; do echo "" >> project_results.txt; done;
            echo "======================================== Default" 2>&1 | tee sanitizers_log.txt
             UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 960 xvfb-run ./godot.linuxbsd.editor.dev.x86_64.san FunctionExecutor.tscn 0 --audio-driver Dummy --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
            tail -n 200 sanitizers_log.txt >> project_results.txt

            if [ -d "CRASH_INFO" ]; then
              echo "CRASH_INFO folder found. Exiting loop."
              break
            fi

            if [ -f "results.txt" ]; then
              if [ -f "results_end.txt" ]; then
                for i in {0..50}; do echo "" >> t.txt; done;
                cat "results.txt" "t.txt" "results_end.txt" > "temp.txt"
                mv "temp.txt" "results_end.txt"
              else
                cp "results.txt" "results_end.txt"
              fi
            fi

            echo "extends Node" > temp.txt
            echo "func _process(delta):" >> temp.txt
            if [ -f results.txt ]; then
              cat temp.txt results.txt > Node.gd.test || true
              UBSAN_OPTIONS=suppressions=suppressions.supp DRI_PRIME=0 timeout -v 3600 ./reproducer godot.linuxbsd.editor.dev.x86_64.san 60_50 . --audio-driver Dummy # || echo "ERROR: REPRODUCER FAILURE"
            fi
           Done

      - name: Store reproducer
        uses: actions/upload-artifact@v3
        with:
          name: reproducer_4_vulkan
          path: crash_reproduce.gd
          if-no-files-found: ignore

      - name: Store report
        uses: actions/upload-artifact@v3
        with:
          name: report_reproducer_4_vulkan
          path: CRASH_INFO
          if-no-files-found: ignore

      - name: Store project results
        uses: actions/upload-artifact@v3
        with:
          name: project-results
          path: project_results.txt

      - name: Store test results
        uses: actions/upload-artifact@v3
        with:
          name: last-run-functions
          path: results_end.txt

      - name: Store timer results
        uses: actions/upload-artifact@v3
        with:
          name: timer
          path: timer_end.txt
          if-no-files-found: ignore

      - name: Store memory usage results
        uses: actions/upload-artifact@v3
        with:
          name: memory-usage
          path: memory_usage_end.txt
          if-no-files-found: ignore

      - name: Check Log
        run: |
          misc/check_ci_log.py project_results.txt
