name: 🐧 Godot 3 GLES2 07 Multithread Rendering TS
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux-sanitizer:
    runs-on: "ubuntu-20.04"
    name: Editor and project

    steps:
      - uses: actions/checkout@v2

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      # Install all packages (except scons)
      - name: Configure dependencies
        run: |
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev \
            libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm \
            xvfb wget2 unzip python scons git

      - name: Configure Data
        run: |
          echo "[rendering]" >> project.godot
          echo "threads/thread_model=2" >> project.godot
          

      - name: Download Godot(GIT)
        run: |
          git clone https://github.com/godotengine/godot.git
          cd godot
          git checkout 3.x
          cd ../

      - name: Compile Godot
        run: |
          cd godot
          scons -j2 use_tsan=yes
          cp bin/godot.x11.tools.64.llvms ../
          cd ../
          rm -rf godot

      - name: Open Godot Editor
        run: |
          DRI_PRIME=0 xvfb-run ./godot.x11.tools.64.llvms -e -q --audio-driver Dummy --video-driver GLES2 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
          tail -n 300 sanitizers_log.txt > editor_results.txt

      - name: Store editor results
        uses: actions/upload-artifact@v2
        with:
          name: editor-results
          path: editor_results.txt

      - name: Check Godot Editor Log
        run: |
          misc/check_ci_log.py sanitizers_log.txt

      - name: Run Project
        run: |
          DRI_PRIME=0 xvfb-run ./godot.x11.tools.64.llvms FunctionExecutor.tscn 3600 --audio-driver Dummy --video-driver GLES2 --path $(pwd) 2>&1 | tee sanitizers_log.txt || true
          tail -n 300 sanitizers_log.txt > project_results.txt

      - name: Store project results
        uses: actions/upload-artifact@v2
        with:
          name: project-results
          path: project_results.txt

      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
          name: last-run-functions
          path: results.txt

      - name: Check Log
        run: |
          misc/check_ci_log.py sanitizers_log.txt